# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "us-east-1"
#  profile = "mohit"
  
  assume_role {
    session_name = "devlab"
    role_arn = "arn:aws:iam::8331359:role/terraform"
  }
}
